/**************************************************************************** 
  *
  * This module contains the definition for all interrupt-handling functions.
  * Such functions are called by the Nucleus in initial.c.
  * 
  * Written by: Kollen Gruizenga and Jake Heyser
  *
  ****************************************************************************/

 #include "../h/asl.h"
 #include "../h/types.h"
 #include "../h/const.h"
 #include "../h/pcb.h"
 #include "../h/scheduler.h"
 #include "../h/interrupts.h"
 #include "../phase2/initial.c"

 /* Function declarations */
 HIDDEN void pltTimerInt(pcb_PTR proc);
 HIDDEN void intTimerInt(pcb_PTR proc);
 HIDDEN void terminalInt(pcb_PTR proc);
 HIDDEN void IOInt(pcb_PTR proc);
 HIDDEN int findDeviceNum(int lineNumber);

 /* Declaring global variables */
 cpu_t curr_tod; /* the current value on the Time of Day clock */
 cpu_t remaining_time; /* the amount of time left on the Current Process' quantum */
 state_PTR savedExceptState; /* a pointer to the saved exception state */

 /* Internal helper function responsible for determining what device number the highest-priority interrupt occurred on. The function
 returns that number to the caller. */
 int findDeviceNum(int lineNumber){
	/* declaring local variables */
	devregarea_t *temp; /* device register area that we can use to determine which device number is associated with the highest-priority interrupt */
	memaddr bitMap; /* the address of the Interrupt Devices Bit Map associated with the line number that was passed in as a parameter */

	/* initializing temp and bitMap in order to determine which device number is associated with the highest-priority interrupt */
	temp = (devregarea_t *) INTDEVICEADDR; /* initialization of temp */
	bitMap = temp->interrupt_dev[lineNumber - OFFSET]; /* initialization of bitMap */

	/* determining which device number is associated with the highest-priority interrupt based on the address of bitMap */
	if (bitMap & DEV0INT != ALLOFF){ /* if there is a pending interrupt associated with device 0 */
		return DEV0; /* returning 0 to the user, since the highest-priority interrupt is associated with device 0 */
	}
	if (bitMap & DEV1INT != ALLOFF){ /* if there is a pending interrupt associated with device 1 */
		return DEV1; /* returning 1 to the user, since the highest-priority interrupt is associated with device 1 */
	}
	if (bitMap & DEV2INT != ALLOFF){ /* if there is a pending interrupt associated with device 2 */
		return DEV2; /* returning 2 to the user, since the highest-priority interrupt is associated with device 2 */
	}
	if (bitMap & DEV3INT != ALLOFF){ /* if there is a pending interrupt associated with device 3 */
		return DEV3; /* returning 3 to the user, since the highest-priority interrupt is associated with device 3 */
	}
	if (bitMap & DEV4INT != ALLOFF){ /* if there is a pending interrupt associated with device 4 */
		return DEV4; /* returning 4 to the user, since the highest-priority interrupt is associated with device 4 */
	}
	if (bitMap & DEV5INT != ALLOFF){ /* if there is a pending interrupt associated with device 5 */
		return DEV5; /* returning 5 to the user, since the highest-priority interrupt is associated with device 5 */
	}
	if (bitMap & DEV6INT != ALLOFF){ /* if there is a pending interrupt associated with device 6 */
		return DEV6; /* returning 6 to the user, since the highest-priority interrupt is associated with device 6 */
	}
	/* otherwise, there is a pending interrupt associated with device 7, since there are only eight devices */
	return DEV7; /* returning 7 to the user, since the highest-priority interrupt is associated with device 7 */
 }

 /* Internal helper function that handles Processor Local Timer (PLT) interrupts */
 void pltTimerInt(pcb_PTR proc){
 	if (proc != NULL){
 		moveState(savedExceptState, &(proc->p_s)); /* moving the updated saved exception state from the BIOS Data Page into the Current Process' processor state */
 		proc->p_time = proc->p_time + (curr_tod - start_tod); /* updating the accumulated processor time used by the Current Process */
 		insertProcQ(&ReadyQueue, proc); /* placing the Current Process back on the Ready Queue because it has not completed its CPU Burst */
		proc->p_s.s_status = ((proc->p_s.s_status) | IECON | IMON); /* re-enabling interrupts for the Current Process */
 		switchProcess(); /* calling the Scheduler to begin execution of the next process on the Ready Queue */
 	}
 	PANIC(); /* otherwise, Current Process is NULL, so the function invokes the PANIC() function to stop the system and print a warning message on terminal 0 */
 }

 /* Internal helper function that handles interrupts generated by the System-wide Interval Timer */
 void intTimerInt(pcb_PTR proc){
 	LDIT(INITIALINTTIMER); /* placing 100 milliseconds back on the Interval Timer for the next Pseudo-clock tick */
 	/* unblocking all pcbs blocked on the Pseudo-Clock semaphore */
	while (headBlocked(&deviceSemaphores[PCLOCKIDX]) != NULL){ /* while the Pseudo-Clock semaphore has a blocked pcb */
		removeBlocked(&deviceSemaphores[PCLOCKIDX]); /* unblock the first (i.e., head) pcb from the Pseudo-Clock semaphore's process queue */
	}
	deviceSemaphores[PCLOCKIDX] = INITIALPCSEM; /* resetting the Pseudo-clock semaphore to zero */
	moveState(savedExceptState, &(proc->p_s)); /* moving the updated saved exception state from the BIOS Data Page into the Current Process' processor state */
	proc->p_time = proc->p_time + (curr_tod - start_tod); /* updating the accumulated processor time used by proc */
	proc->p_s.s_status = ((proc->p_s.s_status) | IECON | IMON); /* re-enabling interrupts for the Current Process */
	if (currentProc != NULL){ /* if there is a Current Process to return control to */
		switchContext(proc); /* calling the function that returns control to the Current Process */
 	}
	switchProcess(); /* if there is no Current Process to return control to, call the Scheduler function to begin executing a new process */
}

/* Internal helper function that handles I/O interrupts on non-terminal devices. In other words, this function handles interrupts that
occurred on lines 3-6 in the Cause register. */
void IOInt(pcb_PTR proc){
	/* delcaring local variables */
	int lineNum; /* the line number that the highest-priority interrupt occurred on */
	int devNum; /* the device number that the highest-priority interrupt occurred on */

	/* determining exactly which line number the interrupt occurred on so we can initialize lineNum */
	if (savedExceptState->s_cause & LINE3INT != ALLOFF){ /* if there is an interrupt on line 3 */
		lineNum = LINE3; /* initializing lineNum to 3, since the highest-priority interrupt occurred on line 3 */
	}
	else if (savedExceptState->s_cause & LINE4INT != ALLOFF){ /* if there is an interrupt on line 4 */
		lineNum = LINE4; /* initializing lineNum to 4, since the highest-priority interrupt occurred on line 4 */
	}
	else if (savedExceptState->s_cause & LINE5INT != ALLOFF){ /* if there is an interrupt on line 5 */
		lineNum = LINE5; /* initializing lineNum to 5, since the highest-priority interrupt occurred on line 5 */
	}
	else if (savedExceptState->s_cause & LINE6INT != ALLOFF){ /* if there is an interrupt on line 6*/
		lineNum = LINE6; /* initializing lineNum to 6, since the highest-priority interrupt occurred on line 6 */
	}
	
	/* initializing devNum by calling the internal function that returns the device number associated with the highest-priority interrupt */
	devNum = findDeviceNum(lineNum);

	/* LEFT OFF HERE */

	
}

 /* Nucleus' device interrupt handler function (exception code 0) */
 void intTrapH(){
 	/* initializing global variables */
 	STCK(curr_tod); /* initializing the current value on the Time of Day clock */
 	remaining_time = getTIMER(); /* initializing the remaining time left on the Current Process' quantum */
	savedExceptState = (state_PTR) BIOSDATAPAGE; /* initializing the saved exception state to the state stored at the start of the BIOS Data Page */

	savedExceptState->s_status = ((savedExceptState->s_status) & IMOFF & IECOFF); /* disabling interrupts for the Current Process */

 	/* calling the appropriate interrupt handler function based off the type of the highest-priority interrupt that occurred */
 	if (savedExceptState->s_cause & LINE1INT != ALLOFF){ /* if there is a PLT interrupt (i.e., an interrupt occurred on line 1) */
 		pltTimerInt(currentProc); /* calling the internal function that handles PLT interrupts */
 	}
 	if (savedExceptState->s_cause & LINE2INT != ALLOFF){ /* if there is a System-Wide Interval Timer/Pseudo-clock interrupt (i.e., an interrupt occurred on line 2) */
 		intTimerInt(currentProc); /* calling the internal function that handles System-Wide Interval Timer/Pseudo-clock interrupts */
 	}
 	if (savedExceptState->s_cause & LINE7INT != ALLOFF){ /* if there is an I/O interrupt on a terminal device (i.e., an interrupt occurred on line 7) */
		terminalInt(currentProc); /* calling the internal function that handles I/O interrupts on terminal devices */
 	}
 	IOInt(currentProc); /* otherwise, an I/O interrupt occurred on a non-terminal device (i.e., an interrupt occurred on lines 3-6) */
 }